<?xml version="1.0" encoding="utf-8"?><Database Name="BiGGData" Class="BiGGDataDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.\SQLEXPRESS;Initial Catalog=BiGGData;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="BiGGDataConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tbl_Admin" Member="tbl_Admins">
    <Type Name="tbl_Admin">
      <Column Name="Username" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.GeneralSettings" Member="GeneralSettings">
    <Type Name="GeneralSetting">
      <Column Name="Favicon" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(70)" CanBeNull="true" />
      <Column Name="MetaDescription" Type="System.String" DbType="NVarChar(180)" CanBeNull="true" />
      <Column Name="MetaKeywords" Type="System.String" DbType="NVarChar(160)" CanBeNull="true" />
    </Type>
  </Table>
</Database>